name: Create a DHIS2 Core instance and cache it

on:
    workflow_dispatch:

jobs:
    cache-instance:
        name: Spin up a DHIS2 Core Docker Stack and cache it
        runs-on: ubuntu-latest
        steps:
            - name: Check out docker files from DHIS2 Core repo
              uses: actions/checkout@v4
              with:
                repository: dhis2/dhis2-core
                sparse-checkout: |
                    docker-compose.yml
                    .dockerignore
                    docker/*
                sparse-checkout-cone-mode: false
            - name: Checkout current repo
              uses: actions/checkout@v4
              with:
                  path: current-repo
            - name: Spin up the stack
              run: |
                docker compose up -d
                sleep 5s
                curl --head -X GET --retry-max-time 300 --retry-connrefused --retry-delay 1 http://127.0.0.1:8080
                docker ps
                docker compose logs web
              env:
                DHIS2_IMAGE: dhis2/core:2.41
                DHIS2_DB_DUMP_URL: https://databases.dhis2.org/sierra-leone/2.38/dhis2-db-sierra-leone.sql.gz
            - name: Install Line Listing App and Generate Analytics Tables
              run: |
                chmod +x ./current-repo/scripts/install-apps-from-app-hub.sh
                chmod +x ./current-repo/scripts/generate-analytics-tables.sh
                ./current-repo/scripts/install-apps-from-app-hub.sh
                ./current-repo/scripts/generate-analytics-tables.sh
              shell: bash
              env:
                BASE_URL: http://127.0.0.1:8080
                USERNAME: admin
                PASSWORD: district
                APPS_TO_INSTALL: 'Line Listing'
            - name: Create cache artefacts dir
              run: mkdir artefacts
            - name: Check file system
              run: ls -l